import numpy as np
a=np.array([1,2,3,4,5,6])
print(a+2)
print(a*2)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.data)
print(a.dtype)

print(np.zeros(5))
print(np.ones(5))
print(np.arange(2,9,1))

print(a[0])
print(a[-1])

print(a[:3])
print(a[::-1])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b[:,2])
print(b[1,:])
print(b[::])
print(b.shape)
print(b.reshape(9,1))
b=b.reshape(3,3)
print(np.sum(a))
c=np.mean(b)
d=np.sum(b)/c
print(d)
mx=np.max(b)
mmx=np.max(b)
mmnx=np.min(b)
mnx=np.min(b)
print(mx,mnx,mmx,mmnx)
print(a[a>5],b[b<5])